# Generated by Django 5.0.3 on 2024-05-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_referal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referal",
            name="point",
            field=models.IntegerField(default=0),
        ),
    ]
