# Generated by Django 5.0.3 on 2024-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_referal_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
