# Generated by Django 5.0.3 on 2024-05-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
