# Generated by Django 5.0.3 on 2024-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone1",
            field=models.IntegerField(null=True),
        ),
    ]
