# Generated by Django 5.0 on 2024-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_profile_phone1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Referal",
        ),
    ]
